/**
 * Parity against the established reference implementations.
 *
 * `test/fixtures/reference.json` is generated by `tools/reference.py` from zadu,
 * scipy and scikit-learn, and is committed so this test needs no Python. Do not
 * hand-edit it: regenerate it if a fixture changes.
 *
 * This is the check that matters most for scientific use. Invariants catch
 * structural bugs; only a reference implementation catches a wrong constant.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, it } from "vitest";
import * as sickle from "../src/index.ts";

const DIR = join(dirname(fileURLToPath(import.meta.url)), "fixtures");
const DATA = join(DIR, "data");

interface FixtureRef {
    n: number;
    [metric: string]: number | number[];
}
const reference = JSON.parse(readFileSync(join(DIR, "reference.json"), "utf8")) as {
    _ks: number[];
    _versions: Record<string, string>;
    fixtures: Record<string, FixtureRef>;
};
const manifest = JSON.parse(readFileSync(join(DATA, "manifest.json"), "utf8")) as Array<{
    name: string;
    description: string;
}>;

function readCsv(path: string): number[][] {
    return readFileSync(path, "utf8")
        .trim()
        .split("\n")
        .map((line) => line.split(",").map(Number));
}

function loadFixture(name: string) {
    return {
        X: readCsv(join(DATA, `${name}.X.csv`)),
        Y: readCsv(join(DATA, `${name}.Y.csv`)),
        labels: readFileSync(join(DATA, `${name}.labels.csv`), "utf8")
            .trim().split("\n").map(Number),
    };
}

/**
 * Exact rank agreement is expected: both sides compute float64 euclidean
 * distances and sort them. The tolerance covers only floating-point summation
 * order, not algorithmic disagreement.
 */
const TOL = 1e-12;

/**
 * Rank measures are under-specified when distances tie. zadu sorts with numpy's
 * default introsort, whose tie order is an implementation detail; sickle breaks
 * ties by point index, which is what `np.argsort(kind="stable")` does. Where the
 * reference recorded that convention, assert against it -- it is the one that is
 * actually defined. On tie-free fixtures the two are bit-identical, so this
 * changes nothing for them.
 */
function expected(ref: FixtureRef, metric: string): number {
    const stable = ref[`${metric.split("@")[0]}__stable@${metric.split("@")[1]}`];
    return (typeof stable === "number" ? stable : ref[metric]) as number;
}

function expectedArray(ref: FixtureRef, metric: string): number[] {
    const stable = ref[`${metric.split("@")[0]}__stable@${metric.split("@")[1]}`];
    return (Array.isArray(stable) ? stable : ref[metric]) as number[];
}

function close(got: number, want: number, tol: number, what: string) {
    const diff = Math.abs(got - want);
    assert.ok(
        diff <= tol * Math.max(1, Math.abs(want)),
        `${what}\n  sickle   ${got}\n  zadu/ref ${want}\n  diff     ${diff}  (tol ${tol})`,
    );
}

describe(`parity with zadu ${reference._versions.zadu} / scipy / sklearn`, () => {
    for (const { name, description } of manifest) {
        const ref = reference.fixtures[name];
        if (!ref) continue;

        describe(`${name} -- ${description}`, () => {
            const { X, Y, labels } = loadFixture(name);
            const hd = sickle.toVectors(X);
            const ld = sickle.toVectors(Y);
            const cr = sickle.coRanking(hd, ld, { localK: [10] });
            const dm = sickle.distanceMoments(hd, ld);
            const cl = sickle.clusters(ld, labels);

            it("agrees on n", () => assert.equal(cr.n, ref.n));

            for (const k of reference._ks) {
                it(`trustworthiness and continuity at k=${k}`, () => {
                    close(sickle.trustworthiness(cr, k), expected(ref, `trustworthiness@${k}`), TOL,
                        `trustworthiness@${k}`);
                    close(sickle.continuity(cr, k), expected(ref, `continuity@${k}`), TOL,
                        `continuity@${k}`);
                });

                it(`MRRE at k=${k}`, () => {
                    close(sickle.mrreFalse(cr, k), expected(ref, `mrre_false@${k}`), TOL,
                        `mrre_false@${k}`);
                    close(sickle.mrreMissing(cr, k), expected(ref, `mrre_missing@${k}`), TOL,
                        `mrre_missing@${k}`);
                });

                it(`neighborhood hit at k=${k}`, () => {
                    // zadu goes through faiss in float32 here, so near-ties can
                    // land differently; allow a little room.
                    close(
                        sickle.neighborhoodHit(ld, labels, k).value,
                        ref[`neighborhood_hit@${k}`] as number,
                        1e-9,
                        `neighborhood_hit@${k}`,
                    );
                });

                it(`LCMC at k=${k}`, () => {
                    // zadu's LCMC path goes through faiss with float32 coordinates,
                    // so near-ties can rank differently; allow a little more room.
                    close(sickle.lcmc(cr, k), ref[`lcmc@${k}`] as number, 1e-9, `lcmc@${k}`);
                });
            }

            it("per-point trustworthiness matches zadu point by point", () => {
                const want = expectedArray(ref, "local_trustworthiness@10");
                const got = sickle.localTrustworthiness(cr, 10);
                assert.equal(got.length, want.length);
                for (let i = 0; i < want.length; ++i) {
                    close(got[i], want[i], TOL, `local_trustworthiness[${i}]`);
                }
            });

            it("per-point continuity matches zadu point by point", () => {
                const want = expectedArray(ref, "local_continuity@10");
                const got = sickle.localContinuity(cr, 10);
                for (let i = 0; i < want.length; ++i) {
                    close(got[i], want[i], TOL, `local_continuity[${i}]`);
                }
            });

            it("the local values still average to the global one", () => {
                const local = sickle.localTrustworthiness(cr, 10);
                let s = 0;
                for (const v of local) s += v;
                close(s / local.length, expected(ref, "trustworthiness@10"), 1e-12, "mean(local)");
            });

            it("stress matches zadu", () => {
                close(sickle.stress(dm).value, ref["stress"] as number, 1e-12, "stress");
            });

            it("scale-normalized stress matches zadu", () => {
                close(
                    sickle.scaleNormalizedStress(dm).value,
                    ref["scale_normalized_stress"] as number,
                    1e-10,
                    "scale_normalized_stress",
                );
                close(sickle.optimalScale(dm), ref["_alpha"] as number, 1e-12, "alpha");
            });

            it("non-metric stress matches zadu", () => {
                close(
                    sickle.nonMetricStress(hd, ld).value,
                    ref["non_metric_stress"] as number,
                    1e-10,
                    "non_metric_stress",
                );
            });

            it("Pearson r matches zadu (full matrix, diagonal included)", () => {
                close(sickle.pearsonR(dm).value, ref["pearson_r"] as number, 1e-11, "pearson_r");
            });

            it("silhouette matches scikit-learn", () => {
                close(sickle.silhouette(ld, cl).value, ref["silhouette"] as number, 1e-11, "silhouette");
            });

            it("Calinski-Harabasz matches scikit-learn", () => {
                close(
                    sickle.calinskiHarabasz(ld, cl).value,
                    ref["calinski_harabasz"] as number,
                    1e-10,
                    "calinski_harabasz",
                );
            });

            it("Spearman rho matches scipy", () => {
                close(sickle.spearmanRho(hd, ld).value, ref["spearman_rho"] as number, 1e-10,
                    "spearman_rho");
            });

            it("residual variance follows from Pearson r", () => {
                const r = ref["pearson_r"] as number;
                close(sickle.residualVariance(dm).value, 1 - r * r, 1e-10, "residual_variance");
            });

            it("Davies-Bouldin matches scikit-learn", () => {
                close(sickle.daviesBouldin(ld, cl).value, ref["davies_bouldin"] as number, 1e-10,
                    "davies_bouldin");
            });

            it("distance consistency matches zadu", () => {
                close(
                    sickle.distanceConsistency(ld, cl).value,
                    ref["distance_consistency"] as number,
                    1e-12,
                    "distance_consistency",
                );
            });

            if (ref["_has_distance_ties"]) {
                // Documents, rather than hides, the one place implementations may
                // legitimately disagree. If this ever stops differing, the fixture
                // has lost its ties and is no longer testing anything.
                it("differs from zadu's arbitrary tie order, by a small amount", () => {
                    const asShipped = ref["trustworthiness@10"] as number;
                    const deterministic = ref["trustworthiness__stable@10"] as number;
                    assert.notEqual(asShipped, deterministic, "fixture no longer contains ties");
                    assert.ok(
                        Math.abs(asShipped - deterministic) < 1e-3,
                        "tie-order divergence is larger than expected; investigate",
                    );
                    close(sickle.trustworthiness(cr, 10), deterministic, TOL, "sickle follows the stable convention");
                });
            }
        });
    }
});
